language: python
python:
- 3.6
install:
- pip install -r requirements.txt
env:
  - APP_SETTINGS=config.StagingConfig
  - DATABASE_URL=postgresql://localhost/thunder_wikibootup
  - CONFIG_SECRET_KEY=needed-to-change
services:
- postgresql
before_script:
- psql -c 'create database thunder_wikibootup;' -U postgres
script:
- py.test -v thunder/
