"""empty message

Revision ID: 0d8e74676dfd
Revises: None
Create Date: 2017-01-05 18:11:49.185523

"""

# revision identifiers, used by Alembic.
revision = '0d8e74676dfd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
